### ISSUE TITLE
Kahroba can't accept function as argument (opposed to Readme)

### ISSUE THREAD

**Issue by arshamalh** [kahroba-lang/kahroba#16]
There is an example in the Readme file that shows Kahroba can accept functions as arguments:
```rust
fn getName() {
    "Kahroba"
}
fn hello(name) {
    println("Hello ", name)
}
hello(getName())
```

But it's not true, in this example, the `getName()` function is executed and its value is passed to the `hello()` function.
This code is totally equivalent of 
```rust
fn getName() {
    "Kahroba"
}
fn hello(name) {
    println("Hello ", name)
}
name = getName() // name is just a value
hello(name)
```

But the correct version of passing functions as arguments should be:
```rust
fn getName() {
    "Kahroba"
}
fn hello(name) {
    println("Hello ", name()) // name is a function!
}
hello(getName)
```

And it causes a golang panic!
```bash
$ ./kahroba main.krb
panic: interface conversion: interface {} is nil, not main.Function

goroutine 1 [running]:
main.FunctionCall.Eval({{0xb7b568, 0xc000104030}, {0xc59ec0, 0x0, 0x0}}, 0x0?)
        ./kahroba/3_eval.go:601 +0x1a7
main.evalExpressions({0xc000102180?, 0x2, 0xb2ff5b?}, 0xc000104120?)
        ./kahroba/3_eval.go:577 +0xb7
main.Print.Eval({{0xc000102180?, 0x0?, 0x0?}, 0x1?}, 0xc000108018?)
        ./kahroba/3_eval.go:562 +0x26
main.Block.Eval({{0xc00010a020?, 0x1?, 0x1?}}, 0xc000100028?)
        ./kahroba/3_eval.go:489 +0x77
main.applyfunction({{0xc000100028, 0x5}, {0xc000106000, 0x1, 0x1}, 0xc000108000, 0xc000092078}, {0xc00010a040, 0x1, 0x1}, ...)
        ./kahroba/3_eval.go:646 +0xa8
main.FunctionCall.Eval({{0xb7b568, 0xc000104090}, {0xc00010a030, 0x1, 0x1}}, 0xc0000860c0?)
        ./kahroba/3_eval.go:603 +0x188
main.Eval(...)
        ./kahroba/3_eval.go:110
main.main()
        ./kahroba/5_main.go:46 +0x151
```

I'm not an expert in writing interpreters, but I think there are two issues here:
1 - In case of panic or error, there should be some clear message, not a panic.
2 - you should remove pass functions as arguments section from readme unless you add this capability.

**Comment by kahroba-lang2** [comment]
آرشام جان همونطور که توی داک هم اومده میشه به عنوان آرگومان فانکشن پاس داد، چیزی که مد نظر تو هست فانکشن به عنوان پارامتره
توی کهربا نمیشه یه پارامتر از نوع فانکشن داشت ولی موقع استفاده از فانکشن میشه یک فانکشن رو به عنوان آرگومان پاس داد
