### ISSUE TITLE
امکان چند شرط برای if

### ISSUE THREAD

**Issue by debuqer** [kahroba-lang/kahroba#24]
امکان قراردادن چند شرط و به طور کلی محاسبه چند شرط به صورت یک گزاره وجود دارد؟
```rust
if a == 1 || b == 2  {
    // do something
}
```

**Comment by me-dira** [comment]
سلام بله، همینطور که میبینید داخل فایل [https://github.com/kahroba-lang/kahroba/blob/main/2_parser.go](url) میتونید اوپراتور هارو مشاهده کنید که اوپراتور (عملگرا) or هم بینشون هست. اما داکیومنتی براش نوشته نشده. @mostafasolati لطف کنین اینو مد نظر داشته باشین با تشکر.

**Comment by mehdi-ra** [comment]
نه فعلا توی این نسخه از این زبان این امکان وجود نداره اما فک کنم بهتره به فیچر لیست اضافه بشه @mostafasolati

**Comment by bistcuite** [comment]
یکم پایتونی تر باشه بهتره : 
```py
if a == 1 and b == 2 {
    // do something
}
```

**Comment by mehdi-ra** [comment]
به نظرتون میشه از اینم ساده ترش کرد ؟

> یکم پایتونی تر باشه بهتره :
> 
> ```python
> if x a == 1 and b == 2 {
>     // do something
> }
> ```
به نظرتون میشه از اینم ساده ترش کرد ؟

**Comment by kahroba-lang2** [comment]
> به نظرتون میشه از اینم ساده ترش کرد ؟
> 
> > یکم پایتونی تر باشه بهتره :
> > ```python
> > if x a == 1 and b == 2 {
> >     // do something
> > }
> > ```
> 
> به نظرتون میشه از اینم ساده ترش کرد ؟

دیگه از این ساده تر سینتکس نا آشنا و عجیب و غریبی از آب در میاد ولی میتونی اگه پیشنهادی داری توی یه ایشو دیگه مطرحش کنی
