### ISSUE TITLE
Run the kahroba program on Linux

### ISSUE THREAD

**Issue by amirmalekian** [kahroba-lang/kahroba#5]
To run the program, it returns a `kahroba: command not found...` error by the command
`kahroba main.kahroba`

**Comment by ar-mokhtari** [comment]
> To run the program, it returns a `kahroba: command not found...` error by the command `kahroba main.kahroba`

![image](https://user-images.githubusercontent.com/49469395/187347528-1f4ea362-5210-4d0c-89b6-7075bfe21c91.png)

**Comment by amirmalekian** [comment]
![kahroba](https://user-images.githubusercontent.com/79522638/187353950-223081ae-68f0-4e54-8b37-fe67f6b7de25.png)

**Comment by ar-mokhtari** [comment]
no need to run command with sudo ...
be sure for permision 
![image](https://user-images.githubusercontent.com/49469395/187398487-301fb543-7966-44ff-a32c-88e3bb32dea9.png)
then run 
![image](https://user-images.githubusercontent.com/49469395/187398989-349a729b-7d95-400e-81b3-ce167c8f9255.png)

**Comment by amirmalekian** [comment]
Thank you :)
Done by ticking the execute field (Allow executing file as program)
