### ISSUE TITLE
identifier ها نمی توانند شامل عدد باشند

### ISSUE THREAD

**Issue by debuqer** [kahroba-lang/kahroba#8]
identifier ها نمیتوانند شامل عدد باشند

```kahroba
a1 = 2

println(a1)
```
خروجی:
```
<nil> 1
```

و همچنین برای فانکشن ها داریم:

```kahroba
rot13(text) {
 println(text)
}

rot13("hello")
```

خروجی:
```
panic: interface conversion: interface {} is int, not main.Function
```

با تشکر

**Comment by kahroba-lang2** [comment]
این مورد فیکس شد 
البته تعریف فانکشن هم که گذاشتی مشکل داره
کلمه کلیدی fn رو نزاشتی قبلش

rot13(text) {
 println(text)
}
